LIRIAS_TYPE_2_LIMO_TYPE = {
    "presentation"         => { :limo => "other", :ris => "ABS" },
    "book"                 => { :limo => "book", :ris => "BOOK"},
    "chapter"              => { :limo => "book_chapter", :ris => "CHAP" },
    "c-bookreview"         => { :limo => "review", :ris => "GEN" },
    "conference"           => { :limo => "conference_proceeding", :ris => "CONF" },
    "design"               => { :limo => "design", :ris => "ART" },
    "dataset"              => { :limo => "research_dataset", :ris => "DATA" },
    "c-editedbook"         => { :limo => "book", :ris => "EDBOOK" },
    "internet-publication" => { :limo => "other", :ris => "WEB" },
    "c-presentation"       => { :limo => "other", :ris => "GEN" },
    "journal-article"      => { :limo => "article", :ris => "JOUR" },
    "other"                => { :limo => "other", :ris => "GEN" },
    "patent"               => { :limo => "patent", :ris => "PAT" },
    "thesis-dissertation"  => { :limo => "dissertation", :ris => "THES" },
    "report"               => { :limo => "text_resource", :ris => "RPRT" },
    "media"                => { :limo => "text_resource", :ris => "GEN" },
    "software"             => { :limo => "other", :ris => "COMP" },
    "c-book"               => { :limo => "text_resource", :ris => "GEN" }
}

LIRIAS_LANGUAGE = {
    "dutch"      => "dut",
    "english"    => "eng",
    "french"     => "fre",
    "nederlands" => "dut",
    "spanish"    => "spa",
    "nl"         => "dut",
    "en_us"      => "eng",
    "eng"        => "eng",
    "en"         => "eng",
    "fr"         => "fre",
    "hungarian"  => "hun",
    "swedish"    => "swe",
    "hebrew"     => "heb",
    "konkani"    => "kok",
    "estonian"   => "est",
    "filipino"   => "fil",
    "pilipino"   => "fil",
    "finnish"    => "fin",
    "bengali"    => "ben",
    "icelandic"  => "ice",
    "romanian"   => "rum",
    "moldovan"   => "rum",
    "moldavian"  => "rum",
    "polish"     => "pol",
    "czech"      => "cze",
    "korean"     => "kor",
    "turkish"    => "tur",
    "norwegian"  => "nor",
    "georgian"   => "geo",
    "danish"     => "dan",
    "arabic"     => "ara",
    "russian"    => "rus",
    "portuguese" => "por",
    "german"     => "ger",
    "italian"    => "ita",
    "catalan"    => "cat",
    "greek"      => "gre",
    "persian"    => "per",
    "uzbek"      => "uzb",
    "ukrainian"  => "ukr",
    "armenian"   => "arm",
    "latin"      => "lat",
    "latvian"    => "lav",
    "chinese"    => "chi",
    "castilian"  => "spa",
    "japanese"   => "jpn",
    "afrikaans"  => "afr",
    "croatian"   => "hrv",
    "slovak"     => "slo",
    "bulgarian"  => "bul",
    "slovenian"  => "slv"
}

FORMAT_MEAN = {
    "archival_material" => "archival_materials",
    "archival_material_manuscript" => "archival_material_manuscripts",
    "edited_book" => "edited_books",
    "newspaper" => "newspapers",
    "computer_file" => "computer_files",
    "journalissue" => "journalissues",
    "offprint" => "articles",
    "patent" => "patents",
    "text_resource" => "text_resources",
    "article" => "articles",
    "other" => "other",
    "journal" => "journals",
    "image" => "images",
    "score" => "scores",
    "audio" => "audios",
    "web_resource" => "web_resources",
    "book" => "books",
    "review" => "reviews",
    "book_chapter" => "book_chapters",
    "internal_report" => "internal_reports",
    "audio-visual" => "audio_visual",
    "conference" => "conferences",
    "chapter" => "book_chapters",
    "game" => "games",
    "standard" => "standards",
    "schoolbook" => "schoolbooks",
    "manuscript" => "manuscripts",
    "external_report" => "external_reports",
    "legal_document" => "legal_documents",
    "video" => "videos",
    "map" => "maps",
    "database" => "databases",
    "statistical_data_set" => "statistical_data_sets",
    "conference_proceeding" => "conference_proceedings",
    "dissertation" => "dissertations",
    "reference_entry" => "reference_entrys",
    "rare_book" => "rare_books",
    "newspaper_article" => "newspaper_articles",
    "government_document" => "government_documents",
    "collection" => "collections",
    "dataset" => "datasets",
    "microform" => "microform"
  }